# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := inspector_protocol_sources
### Rules for action "generateInspectorProtocolSources":
quiet_cmd_inspector_protocol_sources_generateInspectorProtocolSources = ACTION Generating Inspector protocol sources from Inspector.idl $@
cmd_inspector_protocol_sources_generateInspectorProtocolSources = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd third_party/WebKit/Source/WebCore/WebCore.gyp; mkdir -p $(obj)/gen/webkit $(obj)/gen/webcore; python scripts/rule_binding.py ../inspector/Inspector.idl "$(obj)/gen/webcore" "$(obj)/gen/webkit" -- ../bindings/scripts/generate-bindings.pl ../inspector/CodeGeneratorInspector.pm ../bindings/scripts/CodeGenerator.pm ../bindings/scripts/IDLParser.pm ../bindings/scripts/IDLStructure.pm -- --defines "\"ENABLE_3D_CANVAS=1\" \"ENABLE_3D_PLUGIN=1\" \"ENABLE_BLOB=1\" \"ENABLE_BLOB_SLICE=1\" \"ENABLE_CHANNEL_MESSAGING=1\" \"ENABLE_CLIENT_BASED_GEOLOCATION=1\" \"ENABLE_DASHBOARD_SUPPORT=0\" \"ENABLE_DATABASE=1\" \"ENABLE_DATAGRID=0\" \"ENABLE_DEVICE_ORIENTATION=1\" \"ENABLE_DIRECTORY_UPLOAD=1\" \"ENABLE_DOM_STORAGE=1\" \"ENABLE_EVENTSOURCE=1\" \"ENABLE_FILE_SYSTEM=1\" \"ENABLE_FILTERS=1\" \"ENABLE_GEOLOCATION=1\" \"ENABLE_ICONDATABASE=0\" \"ENABLE_INDEXED_DATABASE=1\" \"ENABLE_INPUT_SPEECH=1\" \"ENABLE_JAVASCRIPT_DEBUGGER=1\" \"ENABLE_JSC_MULTIPLE_THREADS=0\" \"ENABLE_LINK_PREFETCH=1\" \"ENABLE_METER_TAG=1\" \"ENABLE_NOTIFICATIONS=1\" \"ENABLE_OFFLINE_WEB_APPLICATIONS=1\" \"ENABLE_OPENTYPE_SANITIZER=1\" \"ENABLE_ORIENTATION_EVENTS=0\" \"ENABLE_PROGRESS_TAG=1\" \"ENABLE_RUBY=1\" \"ENABLE_SANDBOX=1\" \"ENABLE_SHARED_WORKERS=1\" \"ENABLE_SVG=1\" \"ENABLE_SVG_ANIMATION=1\" \"ENABLE_SVG_AS_IMAGE=1\" \"ENABLE_SVG_FONTS=1\" \"ENABLE_SVG_FOREIGN_OBJECT=1\" \"ENABLE_SVG_USE=1\" \"ENABLE_TOUCH_EVENTS=1\" \"ENABLE_V8_SCRIPT_DEBUG_SERVER=1\" \"ENABLE_VIDEO=1\" \"ENABLE_WEB_SOCKETS=1\" \"ENABLE_WEB_TIMING=1\" \"ENABLE_WORKERS=1\" \"ENABLE_XHR_RESPONSE_BLOB=1\" \"ENABLE_XPATH=1\" \"ENABLE_XSLT=1\" \"WTF_USE_WEBP=1\" \"WTF_USE_WEBKIT_IMAGE_DECODERS=1\" \"WTF_USE_ACCELERATED_COMPOSITING=1\" \"ENABLE_3D_RENDERING=1\" \"ENABLE_ACCELERATED_2D_CANVAS=1\" LANGUAGE_JAVASCRIPT" --generator Inspector

$(obj)/gen/webcore/InspectorBackendDispatcher.cpp: obj := $(abs_obj)

$(obj)/gen/webcore/InspectorBackendDispatcher.cpp: builddir := $(abs_builddir)

$(obj)/gen/webcore/InspectorBackendDispatcher.cpp: TOOLSET := $(TOOLSET)
$(obj)/gen/webcore/InspectorBackendDispatcher.cpp: third_party/WebKit/Source/WebCore/bindings/scripts/generate-bindings.pl third_party/WebKit/Source/WebCore/inspector/CodeGeneratorInspector.pm third_party/WebKit/Source/WebCore/bindings/scripts/CodeGenerator.pm third_party/WebKit/Source/WebCore/bindings/scripts/IDLParser.pm third_party/WebKit/Source/WebCore/bindings/scripts/IDLStructure.pm third_party/WebKit/Source/WebCore/inspector/Inspector.idl FORCE_DO_CMD
	$(call do_cmd,inspector_protocol_sources_generateInspectorProtocolSources)
$(obj)/gen/webcore/InspectorBackendStub.js $(obj)/gen/webkit/InspectorBackendDispatcher.h $(obj)/gen/webcore/InspectorFrontend.cpp $(obj)/gen/webkit/InspectorFrontend.h: $(obj)/gen/webcore/InspectorBackendDispatcher.cpp
$(obj)/gen/webcore/InspectorBackendStub.js $(obj)/gen/webkit/InspectorBackendDispatcher.h $(obj)/gen/webcore/InspectorFrontend.cpp $(obj)/gen/webkit/InspectorFrontend.h: ;

all_deps += $(obj)/gen/webcore/InspectorBackendDispatcher.cpp $(obj)/gen/webcore/InspectorBackendStub.js $(obj)/gen/webkit/InspectorBackendDispatcher.h $(obj)/gen/webcore/InspectorFrontend.cpp $(obj)/gen/webkit/InspectorFrontend.h
action_inspector_protocol_sources_generateInspectorProtocolSources_outputs := $(obj)/gen/webcore/InspectorBackendDispatcher.cpp $(obj)/gen/webcore/InspectorBackendStub.js $(obj)/gen/webkit/InspectorBackendDispatcher.h $(obj)/gen/webcore/InspectorFrontend.cpp $(obj)/gen/webkit/InspectorFrontend.h


### Rules for final target.
# Build our special outputs first.
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp: | $(action_inspector_protocol_sources_generateInspectorProtocolSources_outputs)

# Preserve order dependency of special output on deps.
$(action_inspector_protocol_sources_generateInspectorProtocolSources_outputs): | 

$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp
# Add target alias
.PHONY: inspector_protocol_sources
inspector_protocol_sources: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp

# Add target alias to "all" target.
.PHONY: all
all: inspector_protocol_sources

