# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore_bindings
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-I$(obj).$(TOOLSET)/geni \
	-I$(obj)/gen/webcore \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/sqlite \
	-Iv8/include

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-I$(obj).$(TOOLSET)/geni \
	-I$(obj)/gen/webcore \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/sqlite \
	-Iv8/include

OBJS := $(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources1.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources2.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources3.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources4.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources5.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources6.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources7.o \
	$(obj).target/$(TARGET)/gen/webkit/bindings/V8DerivedSources8.o \
	$(obj).target/$(TARGET)/gen/webkit/DocTypeStrings.o \
	$(obj).target/$(TARGET)/gen/webkit/ColorData.o \
	$(obj).target/$(TARGET)/gen/webkit/CSSPropertyNames.o \
	$(obj).target/$(TARGET)/gen/webkit/CSSValueKeywords.o \
	$(obj).target/$(TARGET)/gen/webkit/HTMLElementFactory.o \
	$(obj).target/$(TARGET)/gen/webkit/HTMLNames.o \
	$(obj).target/$(TARGET)/gen/webkit/UserAgentStyleSheetsData.o \
	$(obj).target/$(TARGET)/gen/webkit/V8HTMLElementWrapperFactory.o \
	$(obj).target/$(TARGET)/gen/webkit/XLinkNames.o \
	$(obj).target/$(TARGET)/gen/webkit/XMLNSNames.o \
	$(obj).target/$(TARGET)/gen/webkit/XMLNames.o \
	$(obj).target/$(TARGET)/gen/webkit/SVGNames.o \
	$(obj).target/$(TARGET)/gen/webkit/MathMLElementFactory.o \
	$(obj).target/$(TARGET)/gen/webkit/MathMLNames.o \
	$(obj).target/$(TARGET)/gen/webkit/HTMLEntityTable.o \
	$(obj).target/$(TARGET)/gen/webkit/CSSGrammar.o \
	$(obj).target/$(TARGET)/gen/webkit/XPathGrammar.o \
	$(obj).target/$(TARGET)/gen/webcore/InspectorFrontend.o \
	$(obj).target/$(TARGET)/gen/webcore/InspectorBackendDispatcher.o \
	$(obj).target/$(TARGET)/gen/webkit/SVGElementFactory.o \
	$(obj).target/$(TARGET)/gen/webkit/V8SVGElementWrapperFactory.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_bindings_sources.stamp $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/inspector_protocol_sources.stamp $(obj).target/third_party/npapi/npapi.stamp $(obj).target/v8/tools/gyp/v8.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a: LIBS := $(LIBS)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a
# Add target alias
.PHONY: webcore_bindings
webcore_bindings: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a

# Add target alias to "all" target.
.PHONY: all
all: webcore_bindings

