# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore
### Rules for final target.
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore.stamp: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_remaining.a $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a $(obj).target/third_party/WebKit/Source/JavaScriptCore/JavaScriptCore.gyp/libwtf.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/skia/libskia.a $(obj).target/third_party/npapi/npapi.stamp $(obj).target/v8/tools/gyp/v8.stamp $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore.stamp
# Add target alias
.PHONY: webcore
webcore: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore.stamp

# Add target alias to "all" target.
.PHONY: all
all: webcore

