# This file is generated by gyp; do not edit.

export builddir_name ?= /home/slv/chromium/home/chrome-svn/tarball/chromium/src/third_party/WebKit/Source/WebCore/WebCore.gyp/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. inspector_protocol_sources webcore_bindings_sources webcore_bindings webcore_prerequisites webcore_remaining webcore_html webcore_platform webcore_svg webcore
