# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore_prerequisites
### Rules for final target.
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_bindings.a $(obj).target/third_party/WebKit/Source/JavaScriptCore/JavaScriptCore.gyp/libpcre.a $(obj).target/third_party/WebKit/Source/JavaScriptCore/JavaScriptCore.gyp/libwtf.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/skia/libskia.a $(obj).target/third_party/iccjpeg/libiccjpeg.a $(obj).target/third_party/libwebp/libwebp.a $(obj).target/third_party/libxml/libxml2.a $(obj).target/third_party/libxslt/libxslt.a $(obj).target/third_party/npapi/npapi.stamp $(obj).target/third_party/ots/libots.a $(obj).target/third_party/sqlite/libsqlite3.a $(obj).target/third_party/angle/src/libtranslator_common.a $(obj).target/v8/tools/gyp/v8.stamp $(obj).target/gpu/libgles2_c_lib.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp
# Add target alias
.PHONY: webcore_prerequisites
webcore_prerequisites: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp

# Add target alias to "all" target.
.PHONY: all
all: webcore_prerequisites

