# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore_html
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include

OBJS := $(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/AsyncImageResizer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/BaseButtonInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/BaseCheckableInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/BaseDateAndTimeInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/BaseTextInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ButtonInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/CheckboxInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ClassList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/CollectionCache.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ColorInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DOMDataGridDataSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DOMFormData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DOMSettableTokenList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DOMTokenList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DataGridColumn.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DataGridColumnList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DateComponents.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DateInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DateTimeInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/DateTimeLocalInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/EmailInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/FTPDirectoryDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/FileInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/FormAssociatedElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/FormDataList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLAllCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLAnchorElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLAppletElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLAreaElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLAudioElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLBRElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLBaseElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLBaseFontElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLBlockquoteElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLBodyElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLButtonElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLCanvasElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDListElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDataGridCellElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDataGridColElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDataGridElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDataGridRowElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDataListElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDetailsElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDirectoryElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDivElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLEmbedElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFieldSetElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFontElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFormCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFormControlElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFormElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFrameElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFrameElementBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFrameOwnerElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLFrameSetElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLHRElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLHeadElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLHeadingElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLHtmlElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLIFrameElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLImageElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLImageLoader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLInputElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLIsIndexElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLKeygenElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLLIElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLLabelElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLLegendElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLLinkElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMapElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMarqueeElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMediaElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMenuElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMetaElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLMeterElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLModElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLNameCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLOListElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLObjectElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLOptGroupElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLOptionElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLOptionsCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLOutputElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLParagraphElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLParamElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLParserErrorCodes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLPlugInElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLPlugInImageElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLPreElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLProgressElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLQuoteElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLScriptElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLSelectElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLSourceElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLStyleElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableCaptionElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableCellElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableColElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTablePartElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableRowElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableRowsCollection.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTableSectionElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTextAreaElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLTitleElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLUListElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLVideoElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HTMLViewSourceDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/HiddenInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ImageData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ImageDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ImageInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ImageResizerThread.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/InputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/IsIndexInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/LabelsNodeList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/MediaDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/MonthInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/NumberInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/PasswordInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/PluginDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/RadioInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/RangeInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ResetInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/SearchInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/StepRange.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/SubmitInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TelephoneInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TextDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TextFieldInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TextInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TimeInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/TimeRanges.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/URLInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ValidationMessage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/ValidityState.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/WeekInputType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/ArrayBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/ArrayBufferView.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasContextAttributes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasGradient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasPattern.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasPixelArray.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasRenderingContext.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasRenderingContext2D.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/CanvasStyle.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/DataView.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Float32Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Int16Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Int32Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Int8Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/OESTextureFloat.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Uint16Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Uint32Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/Uint8Array.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLContextAttributes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLContextEvent.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLExtension.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLFramebuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLGetInfo.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLProgram.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLRenderbuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLRenderingContext.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLShader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLTexture.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebGLUniformLocation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/canvas/WebKitLoseContext.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/CSSPreloadScanner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLConstructionSite.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLDocumentParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLElementStack.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLEntityParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLEntitySearch.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLFormattingElementList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLMetaCharsetParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLParserIdioms.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLParserScheduler.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLPreloadScanner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLScriptRunner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLTokenizer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLTreeBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/HTMLViewSourceParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/TextDocumentParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/parser/TextViewSourceParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/html/shadow/SliderThumbElement.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a: LIBS := $(LIBS)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a
# Add target alias
.PHONY: webcore_html
webcore_html: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_html.a

# Add target alias to "all" target.
.PHONY: all
all: webcore_html

