# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore_platform
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include \
	-Ithird_party/harfbuzz/contrib \
	-Ithird_party/harfbuzz/src

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include \
	-Ithird_party/harfbuzz/contrib \
	-Ithird_party/harfbuzz/src

OBJS := $(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioBus.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioChannel.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioDSPKernelProcessor.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioResampler.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioResamplerKernel.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/AudioUtilities.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/Biquad.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/Cone.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/Distance.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/EqualPowerPanner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/FFTConvolver.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/FFTFrame.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/HRTFDatabase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/HRTFDatabaseLoader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/HRTFElevation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/HRTFKernel.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/HRTFPanner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/Panner.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/Reverb.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/ReverbConvolver.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/ReverbAccumulationBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/ReverbConvolverStage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/ReverbInputBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/VectorMath.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/audio/chromium/AudioBusChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/animation/Animation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/animation/AnimationList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ChromiumDataObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ChromiumDataObjectLegacy.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ClipboardChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ClipboardChromiumLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ClipboardMimeTypes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ClipboardUtilitiesChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ContextMenuChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ContextMenuItemChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/CursorChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/DragDataChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/DragImageChromiumSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/FileChooserChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/FileSystemChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/FileSystemChromiumLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/FramelessScrollView.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/KeyCodeConversionGtk.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/LanguageChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/LinkHashChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/MIMETypeRegistryChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/PasteboardChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/PlatformKeyboardEventChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/PlatformScreenChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/PlatformThemeChromiumGtk.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/PopupMenuChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ReadableDataObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SSLKeyGeneratorChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ScrollbarThemeChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/ScrollbarThemeChromiumLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SearchPopupMenuChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SharedTimerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SoundChromiumPosix.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SuddenTerminationChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/SystemTimeChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/TemporaryLinkStubs.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/WidgetChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/chromium/WritableDataObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/Canvas2DLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/CanvasLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/ComplexTextControllerLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/ContentLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/DrawingBufferChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/FontCacheLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/FontLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/FontPlatformDataLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/GLES2Canvas.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/GraphicsLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/HarfbuzzSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/IconChromiumLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/ImageChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/ImageLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/LayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/LayerRendererChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/LayerTexture.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/LayerTilerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/PluginLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/RenderSurfaceChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/SimpleFontDataLinux.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/TextureManager.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/VideoFrameChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/VideoLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/VDMXParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/WebGLLayerChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEBlend.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEColorMatrix.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEComponentTransfer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEComposite.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEConvolveMatrix.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEDiffuseLighting.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEDisplacementMap.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEFlood.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEGaussianBlur.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FELighting.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEMerge.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEMorphology.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FEOffset.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FESpecularLighting.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FETile.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FETurbulence.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/LightSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/FilterEffect.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/SourceAlpha.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/filters/SourceGraphic.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/DrawingBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/SharedGraphicsContext3D.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/Shader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/SolidFillShader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/TexShader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/Texture.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/gpu/TilingData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/MediaPlayer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/opentype/OpenTypeSanitizer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/FloatPointSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/FloatRectSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/FontCustomPlatformData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/GlyphPageTreeNodeSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/GradientSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/GraphicsContextSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/GraphicsContext3DSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/ImageBufferSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/ImageSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/IntPointSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/IntRectSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/NativeImageSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/PathSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/PatternSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/PlatformContextSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/SkiaUtils.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/skia/TransformationMatrixSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/AffineTransform.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/Matrix3DTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/MatrixTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/PerspectiveTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/RotateTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/ScaleTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/SkewTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/TransformOperations.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/TransformationMatrix.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/transforms/TranslateTransformOperation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/BitmapImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Color.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FloatPoint.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FloatPoint3D.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FloatQuad.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FloatRect.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FloatSize.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Font.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontCache.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontDescription.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontFallbackList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontFamily.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/FontFastPath.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GeneratedImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GlyphPageTreeNode.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Gradient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GraphicsContext.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GraphicsContext3D.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GraphicsLayer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/GraphicsTypes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Image.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/ImageBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/ImageSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/IntRect.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Path.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/PathTraversalState.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/Pattern.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/SegmentedFontData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/SimpleFontData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/StringTruncator.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/graphics/WidthIterator.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/ImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/bmp/BMPImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/bmp/BMPImageReader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/gif/GIFImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/gif/GIFImageReader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/ico/ICOImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/jpeg/JPEGImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/webp/WEBPImageDecoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-decoders/skia/ImageDecoderSkia.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-encoders/skia/JPEGImageEncoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/image-encoders/skia/PNGImageEncoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/AuthenticationChallengeChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/CookieJarChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/DNSChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/NetworkStateNotifierChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/ResourceRequest.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/chromium/ResourceResponse.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/AuthenticationChallengeBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/BlobData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/Credential.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/DataURL.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/FormData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/FormDataBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/HTTPHeaderMap.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/HTTPParsers.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/NetworkStateNotifier.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/ProtectionSpace.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/ResourceErrorBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/ResourceRequestBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/ResourceResponseBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/SocketStreamErrorBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/network/SocketStreamHandleBase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/SQLValue.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/SQLiteAuthorizer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/SQLiteDatabase.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/SQLiteStatement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/SQLiteTransaction.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/chromium/SQLiteFileSystemChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/sql/chromium/SQLiteFileSystemChromiumPosix.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/chromium/TextBreakIteratorInternalICUChromium.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/transcoder/FontTranscoder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/Base64.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/BidiContext.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/Hyphenation.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/LineEnding.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/RegularExpression.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/SegmentedString.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/String.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextBoundaries.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextBreakIteratorICU.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextCodec.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextCodecICU.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextCodecLatin1.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextCodecUTF16.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextCodecUserDefined.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextEncoding.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextEncodingDetectorICU.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextEncodingRegistry.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/TextStream.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/text/UnicodeRange.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Arena.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/AsyncFileSystem.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ContentType.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/CrossThreadCopier.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/DeprecatedPtrListImpl.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/DragData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/DragImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/FileChooser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/FileStream.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/FileSystem.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/GeolocationService.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/KillRingNone.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/KURLGoogle.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Language.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Length.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Logging.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/mock/DeviceOrientationClientMock.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/mock/GeolocationClientMock.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/mock/GeolocationServiceMock.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/mock/SpeechInputClientMock.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ScrollAnimator.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ScrollView.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/SchemeRegistry.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Scrollbar.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ScrollbarClient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ScrollbarThemeComposite.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/SecureTextInput.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/SharedBuffer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ThreadGlobalData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/ThreadTimers.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Timer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/UUID.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/platform/Widget.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a: LIBS := $(LIBS)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a
# Add target alias
.PHONY: webcore_platform
webcore_platform: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_platform.a

# Add target alias to "all" target.
.PHONY: all
all: webcore_platform

