# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webcore_svg
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DENABLE_3D_CANVAS=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CLIENT_BASED_GEOLOCATION=1' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATABASE=1' \
	'-DENABLE_DATAGRID=0' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM_STORAGE=1' \
	'-DENABLE_EVENTSOURCE=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_SPEECH=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JSC_MULTIPLE_THREADS=0' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_METER_TAG=1' \
	'-DENABLE_NOTIFICATIONS=1' \
	'-DENABLE_OFFLINE_WEB_APPLICATIONS=1' \
	'-DENABLE_OPENTYPE_SANITIZER=1' \
	'-DENABLE_ORIENTATION_EVENTS=0' \
	'-DENABLE_PROGRESS_TAG=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_ANIMATION=1' \
	'-DENABLE_SVG_AS_IMAGE=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_SVG_FOREIGN_OBJECT=1' \
	'-DENABLE_SVG_USE=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XPATH=1' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-DUSE_SYSTEM_LIBPNG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-I/usr/include/libpng12 \
	-pthread \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-Igpu \
	-I$(obj).$(TOOLSET)/geni \
	-Ithird_party/WebKit/Source/WebCore \
	-Ithird_party/WebKit/Source/WebCore/accessibility \
	-Ithird_party/WebKit/Source/WebCore/accessibility/chromium \
	-Ithird_party/WebKit/Source/WebCore/bindings \
	-Ithird_party/WebKit/Source/WebCore/bindings/generic \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8 \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/custom \
	-Ithird_party/WebKit/Source/WebCore/bindings/v8/specialization \
	-Ithird_party/WebKit/Source/WebCore/css \
	-Ithird_party/WebKit/Source/WebCore/dom \
	-Ithird_party/WebKit/Source/WebCore/dom/default \
	-Ithird_party/WebKit/Source/WebCore/editing \
	-Ithird_party/WebKit/Source/WebCore/fileapi \
	-Ithird_party/WebKit/Source/WebCore/history \
	-Ithird_party/WebKit/Source/WebCore/html \
	-Ithird_party/WebKit/Source/WebCore/html/canvas \
	-Ithird_party/WebKit/Source/WebCore/html/parser \
	-Ithird_party/WebKit/Source/WebCore/html/shadow \
	-Ithird_party/WebKit/Source/WebCore/inspector \
	-Ithird_party/WebKit/Source/WebCore/loader \
	-Ithird_party/WebKit/Source/WebCore/loader/appcache \
	-Ithird_party/WebKit/Source/WebCore/loader/archive \
	-Ithird_party/WebKit/Source/WebCore/loader/cache \
	-Ithird_party/WebKit/Source/WebCore/loader/icon \
	-Ithird_party/WebKit/Source/WebCore/mathml \
	-Ithird_party/WebKit/Source/WebCore/notifications \
	-Ithird_party/WebKit/Source/WebCore/page \
	-Ithird_party/WebKit/Source/WebCore/page/animation \
	-Ithird_party/WebKit/Source/WebCore/page/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform \
	-Ithird_party/WebKit/Source/WebCore/platform/animation \
	-Ithird_party/WebKit/Source/WebCore/platform/audio \
	-Ithird_party/WebKit/Source/WebCore/platform/audio/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/gpu \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/opentype \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/graphics/transforms \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/png \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/xbm \
	-Ithird_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	-Ithird_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	-Ithird_party/WebKit/Source/WebCore/platform/mock \
	-Ithird_party/WebKit/Source/WebCore/platform/network \
	-Ithird_party/WebKit/Source/WebCore/platform/network/chromium \
	-Ithird_party/WebKit/Source/WebCore/platform/sql \
	-Ithird_party/WebKit/Source/WebCore/platform/text \
	-Ithird_party/WebKit/Source/WebCore/platform/text/transcoder \
	-Ithird_party/WebKit/Source/WebCore/plugins \
	-Ithird_party/WebKit/Source/WebCore/plugins/chromium \
	-Ithird_party/WebKit/Source/WebCore/rendering \
	-Ithird_party/WebKit/Source/WebCore/rendering/style \
	-Ithird_party/WebKit/Source/WebCore/rendering/svg \
	-Ithird_party/WebKit/Source/WebCore/storage \
	-Ithird_party/WebKit/Source/WebCore/storage/chromium \
	-Ithird_party/WebKit/Source/WebCore/svg \
	-Ithird_party/WebKit/Source/WebCore/svg/animation \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics \
	-Ithird_party/WebKit/Source/WebCore/svg/graphics/filters \
	-Ithird_party/WebKit/Source/WebCore/svg/properties \
	-Ithird_party/WebKit/Source/WebCore/webaudio \
	-Ithird_party/WebKit/Source/WebCore/websockets \
	-Ithird_party/WebKit/Source/WebCore/workers \
	-Ithird_party/WebKit/Source/WebCore/xml \
	-Ithird_party/angle/include/GLSLANG \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/webkit/bindings \
	-Ithird_party/WebKit/Source/JavaScriptCore \
	-Ithird_party/WebKit/Source/JavaScriptCore/wtf \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Iskia/ext \
	-Ithird_party/iccjpeg \
	-Ithird_party/libwebp \
	-Ithird_party/libwebp/webp \
	-Ithird_party/libxml/linux/include \
	-Ithird_party/libxml/src/include \
	-Ithird_party/libxslt \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Ithird_party/ots/include \
	-Ithird_party/sqlite \
	-Iv8/include

OBJS := $(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/style/SVGRenderStyle.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/style/SVGRenderStyleDefs.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGBlock.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGForeignObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGGradientStop.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGHiddenContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGInline.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGInlineText.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGModelObject.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGPath.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceClipper.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceFilter.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceFilterPrimitive.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceGradient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceLinearGradient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceMarker.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceMasker.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourcePattern.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceRadialGradient.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGResourceSolidColor.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGRoot.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGShadowTreeRootContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGTSpan.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGText.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGTextPath.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGTransformableContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/RenderSVGViewportContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGImageBufferTools.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGInlineFlowBox.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGInlineTextBox.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGMarkerLayoutInfo.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGRenderSupport.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGRenderTreeAsText.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGResources.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGResourcesCache.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGResourcesCycleSolver.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGRootInlineBox.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGShadowTreeElements.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextChunk.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextChunkBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextLayoutAttributes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextLayoutAttributesBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextLayoutEngine.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextLayoutEngineBaseline.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextLayoutEngineSpacing.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextMetrics.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/rendering/svg/SVGTextQuery.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/animation/SMILTime.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/animation/SMILTimeContainer.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/animation/SVGSMILElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/graphics/filters/SVGFEImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/graphics/filters/SVGFilter.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/graphics/filters/SVGFilterBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/graphics/SVGImage.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/properties/SVGPathSegListPropertyTearOff.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/ColorDistance.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAltGlyphElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAngle.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAnimateColorElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAnimateElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAnimateMotionElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAnimateTransformElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGAnimationElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGCircleElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGClipPathElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGColor.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGComponentTransferFunctionElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGCursorElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGDefsElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGDescElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGDocument.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGDocumentExtensions.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGElementInstance.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGElementInstanceList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGEllipseElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGExternalResourcesRequired.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEBlendElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEColorMatrixElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEComponentTransferElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFECompositeElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEConvolveMatrixElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEDiffuseLightingElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEDisplacementMapElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEDistantLightElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEFloodElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEFuncAElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEFuncBElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEFuncGElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEFuncRElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEGaussianBlurElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEImageElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFELightElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEMergeElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEMergeNodeElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEMorphologyElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEOffsetElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFEPointLightElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFESpecularLightingElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFESpotLightElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFETileElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFETurbulenceElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFilterElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFilterPrimitiveStandardAttributes.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFitToViewBox.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFont.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontData.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontFaceElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontFaceFormatElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontFaceNameElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontFaceSrcElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGFontFaceUriElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGForeignObjectElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGGElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGGlyphElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGGradientElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGHKernElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGImageElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGImageLoader.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLangSpace.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLength.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLengthList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLineElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLinearGradientElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGLocatable.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGMPathElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGMarkerElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGMaskElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGMetadataElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGMissingGlyphElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGNumberList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPaint.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGParserUtilities.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathBlender.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathByteStreamBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathByteStreamSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathParser.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathParserFactory.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathSegList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathSegListBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathSegListSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathStringBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathStringSource.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPathTraversalStateBuilder.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPatternElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPointList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPolyElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPolygonElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPolylineElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGPreserveAspectRatio.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGRadialGradientElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGRectElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGSVGElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGScriptElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGSetElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStopElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStringList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStylable.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStyleElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStyledElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStyledLocatableElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGStyledTransformableElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGSwitchElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGSymbolElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTRefElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTSpanElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTests.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTextContentElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTextElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTextPathElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTextPositioningElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTitleElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTransform.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTransformDistance.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTransformList.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGTransformable.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGURIReference.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGUseElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGViewElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGViewSpec.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGVKernElement.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGZoomAndPan.o \
	$(obj).target/$(TARGET)/third_party/WebKit/Source/WebCore/svg/SVGZoomEvent.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/webcore_prerequisites.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a: LIBS := $(LIBS)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a: TOOLSET := $(TOOLSET)
$(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a
# Add target alias
.PHONY: webcore_svg
webcore_svg: $(obj).target/third_party/WebKit/Source/WebCore/WebCore.gyp/libwebcore_svg.a

# Add target alias to "all" target.
.PHONY: all
all: webcore_svg

